import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import style from './Layout.module.css'
import cn from 'classnames'
import { Header } from "@/components/Header/Header";
import { Sidebar } from "@/components/Sidebar/Sidebar";
import { Footer } from "@/components/Footer/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Header />
          <div>
              <Sidebar />
              <div>
                  {children}
              </div>
          </div>
        <Footer />
      </body>
    </html>
  );
}
