import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";
import styles from '../layout.module.css'
import { Header } from "@/components/Header/Header";
import { Footer } from "@/components/Footer/Footer";
import { Up } from "@/components/Up/Up";
import { getMenuItem } from "@/api/menu";
import Metrika from "@/components/Metrika/Metrika";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menu = await getMenuItem(0)
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={styles.wrapper}>
          <Header className={styles.header} menu={menu}/>
          {children}
          <Footer className={styles.footer}/>
          <Up />
          <Metrika />
        </div>
      </body>
    </html>
  );
}
